CC        := x86_64-elf-gcc
LD        := x86_64-elf-ld
OBJCOPY   := x86_64-elf-objcopy
READELF   := x86_64-elf-readelf
NASM      := nasm
NASMFLAGS := -f elf64

#only used for Lz4
HOSTCC    := gcc

KERNEL         := build/ckImage
IMAGE          := OSFIX.img
IMAGE_SIZE_MB  := 64

OVMF_CODE := /usr/share/edk2/x64/OVMF_CODE.4m.fd
OVMF_VARS := /usr/share/edk2/x64/OVMF_VARS.4m.fd

CFLAGS  := -Iboot/limine \
           -Ikernel \
           -Ikernel/utils/libs/includes \
           -Ikernel/utils/print/includes \
           -Ikernel/utils/misc/includes \
           -Ikernel/utils/terminal \
           -Ikernel/utils/decompressor/includes \
           -Ikernel/mm/includes \
           -Ikernel/arch/x86_64/includes \
           -Ikernel/utils/terminal \
           -Ikernel/utils/time/includes \
           -Ikernel/fs/fsm/includes \
           -Ikernel/fs/fsm/includes/initramfs \
           -Ibuild \
           -I. \
           -Wall -Wextra -std=gnu11 -ffreestanding -fno-stack-protector \
           -fno-stack-check -fno-lto -fno-pie -fno-pic \
           -m64 -march=x86-64 -mno-80387 -mno-mmx \
           -mno-red-zone -mcmodel=kernel

# kernel compression, two-stage boot:

#   1. "real kernel" (kernel/*)  > build/kernel_real.elf > flattened to
#      build/kernel_real.bin > lz4-compressed to build/kernel_real.bin.lz4
#      > embedded as an object file, build/kernel_blob.o

#   2. "stub" (boot/stub/stub.c + the LZ4 decompressor + memcpy/memmove)
#      is linked together with build/kernel_blob.o into build/ckImage

#      THIS is the only thing limine ever boots. At boot it decompresses
#      the real kernel into a reserved memory region and jumps to it.

CKIMAGE_ELF     := build/kernel_real.elf
CKIMAGE_BIN     := build/kernel_real.bin
CKIMAGE_LZ4     := build/ckImage.lz4
KERNEL_BLOB_OBJ     := build/kernel_blob.o
KERNEL_META_HEADER  := build/kernel_meta.h
LZ4ENC_HOST_TOOL    := build/lz4enc

CKIMAGE_LDFLAGS := -T kernel/linker.ld -nostdlib -static \
                       -z max-page-size=0x1000 -no-pie

STUB_LDFLAGS := -T boot/stub/linker.ld -nostdlib -static \
                -z max-page-size=0x1000 -no-pie --no-warn-rwx-segments

CKIMAGE_C_SOURCES   := $(shell find kernel -name "*.c" -not -path "kernel/utils/decompressor/*")
CKIMAGE_ASM_SOURCES := $(shell find kernel -name "*.asm")
CKIMAGE_C_OBJECTS   := $(CKIMAGE_C_SOURCES:%.c=build/%.o)
CKIMAGE_ASM_OBJECTS := $(CKIMAGE_ASM_SOURCES:%.asm=build/%.o)
CKIMAGE_OBJECTS     := $(CKIMAGE_C_OBJECTS) $(CKIMAGE_ASM_OBJECTS)

STUB_C_SOURCES := boot/stub/stub.c \
                  kernel/utils/decompressor/lz4.c \
                  kernel/utils/libs/string.c
STUB_OBJECTS   := $(STUB_C_SOURCES:%.c=build/%.o)

.PHONY: all clean run image

all: clean $(KERNEL)

build/%.o: %.c
	@echo "  CC     $<"
	@mkdir -p $(dir $@)
	@$(CC) $(CFLAGS) -c $< -o $@

build/%.o: %.asm
	@echo "  NASM   $<"
	@mkdir -p $(dir $@)
	@$(NASM) $(NASMFLAGS) $< -o $@

# stub.c pulls in the entry-point/size constants generated below.
build/boot/stub/stub.o: $(KERNEL_META_HEADER)

#/--/--/--/--/--/--/--/--/--/ Now this is where the real fun begins /--/--/--/--/--/--/--/--/--/

#Stage 1: Build the main kernel
$(CKIMAGE_ELF): $(CKIMAGE_OBJECTS)
	@mkdir -p $(dir $@)
	@echo "  LD     $@ (real kernel)"
	@$(LD) $(CKIMAGE_LDFLAGS) -o $@ $(CKIMAGE_OBJECTS)

$(CKIMAGE_BIN): $(CKIMAGE_ELF)
	@echo "  OBJCOPY $@"
	@$(OBJCOPY) -O binary $< $@


#Stage 2: Compress the kernel
$(LZ4ENC_HOST_TOOL): tools/lz4enc.c
	@mkdir -p $(dir $@)
	@echo "  HOSTCC $@"
	@$(HOSTCC) -O2 -Wall -Wextra -o $@ $<

$(CKIMAGE_LZ4): $(CKIMAGE_BIN) $(LZ4ENC_HOST_TOOL)
	@echo "  LZ4    $@"
	@$(LZ4ENC_HOST_TOOL) $(CKIMAGE_BIN) $(CKIMAGE_LZ4)


#Stage 3: Shove the compressed kernel inside of an elf
$(KERNEL_BLOB_OBJ): $(CKIMAGE_LZ4)
	@echo "  OBJCOPY $@ (embed compressed kernel)"
	@$(OBJCOPY) -I binary -O elf64-x86-64 -B i386:x86-64 \
	    --rename-section .data=.compressed_kernel \
	    $< $@


#Stage 3A: real kernel's entry point + raw size
$(KERNEL_META_HEADER): $(CKIMAGE_ELF) $(CKIMAGE_BIN)
	@mkdir -p $(dir $@)
	@echo "  GEN    $@"
	@entry=$$($(READELF) -h $(CKIMAGE_ELF) | grep "Entry point address" | awk '{print $$NF}'); \
	 rawsize=$$(wc -c < $(CKIMAGE_BIN)); \
	 echo "// auto-generated by Makefile; do not edit " > $@; \
	 echo "#define CKIMAGE_ENTRY $${entry}UL" >> $@; \
	 echo "#define CKIMAGE_RAW_SIZE $${rawsize}" >> $@


#Stage 4: Finally, link everything together.
$(KERNEL): $(STUB_OBJECTS) $(KERNEL_BLOB_OBJ)
	@mkdir -p $(dir $@)
	@echo "  LD     $@ (stub)"
	@$(LD) $(STUB_LDFLAGS) -o $@ $(STUB_OBJECTS) $(KERNEL_BLOB_OBJ)

	@printf "\033[32mKernel: $(KERNEL) is ready for use\033[0m\n"

#End fun :(

image: $(KERNEL)
	@rm -f $(IMAGE)
	@dd if=/dev/zero of=$(IMAGE) bs=1M count=$(IMAGE_SIZE_MB)
	@mkfs.fat -F 32 $(IMAGE)
	@mmd -i $(IMAGE) ::/EFI
	@mmd -i $(IMAGE) ::/EFI/BOOT
	@mmd -i $(IMAGE) ::/boot
	@mmd -i $(IMAGE) ::/boot/limine
	@mcopy -i $(IMAGE) boot/limine/BOOTX64.EFI ::/EFI/BOOT/
	@mcopy -i $(IMAGE) $(KERNEL) ::/boot/ckImage
	@mcopy -i $(IMAGE) boot/limine/assets/limine.conf ::/boot/limine/

run: image
	@cp $(OVMF_VARS) build/OVMF_VARS.fd
	@qemu-system-x86_64 \
		-drive if=pflash,format=raw,unit=0,file=$(OVMF_CODE),readonly=on \
		-drive if=pflash,format=raw,unit=1,file=build/OVMF_VARS.fd \
		-drive file=$(IMAGE),format=raw \
		-serial stdio -m 512M

clean:
	@rm -rf build $(IMAGE)
