#this just turns `nm -n kernel.elf` text output (already filtered to text symbols by the Makefile) into a sorted, linkable KSym_t array.
#despite my hate that is fueled by a thousand suns for python, it is surprisingly useful for diry-work like this.
import sys

def main():
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} <ksyms.txt> <ksyms_data.c>", file=sys.stderr)
        sys.exit(1)

    src_path, out_path = sys.argv[1], sys.argv[2]

    entries = []
    with open(src_path) as f:
        for line in f:
            parts = line.split()
            if len(parts) != 2:
                continue
            addr, name = parts
            entries.append((int(addr, 16), name))

    # nm -n already sorts ascending, but dont trust it like a FUCKING FOOL
    entries.sort(key=lambda e: e[0])

    with open(out_path, "w") as out:
        out.write("//auto-generated by Makefile (pass 1 from tools/gen_ksyms.py); do not edit.\n")
        out.write("#include <ksyms.h>\n\n")
        if entries:
            out.write("const KSym_t g_ksyms[] = {\n")
            for addr, name in entries:
                out.write(f'    {{ 0x{addr:x}ULL, "{name}" }},\n')
            out.write("};\n")
        else:
            out.write("const KSym_t g_ksyms[] = {\n    { 0, \"?\" },\n};\n")
        out.write(f"const uint64_t g_ksyms_count = {len(entries)};\n")

if __name__ == "__main__":
    main()

#ew, python